# Generated by Django 4.2.5 on 2024-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='preview',
            field=models.CharField(default='', max_length=255),
        ),
    ]
