# Generated by Django 5.0 on 2023-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture_url',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
