# Generated by Django 5.0 on 2023-12-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_category_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture_url',
            field=models.CharField(max_length=300),
        ),
    ]
