# Generated by Django 5.0 on 2023-12-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_order_picture1_remove_order_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pictures',
            field=models.ImageField(default='circuit.png', upload_to='images/'),
        ),
    ]
