# Generated by Django 5.0 on 2023-12-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_category_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
