# Generated by Django 5.0 on 2023-12-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_order_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pictures',
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(default='images/sedan.png', upload_to='images/')),
                ('picture2', models.ImageField(default='images/sedan.png', upload_to='images/')),
                ('picture3', models.ImageField(default='images/sedan.png', upload_to='images/')),
                ('picture4', models.ImageField(default='images/sedan.png', upload_to='images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.order')),
            ],
        ),
    ]
