# Generated by Django 5.0 on 2023-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_order_pictures_orderattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderattachment',
            options={'verbose_name_plural': 'OrderAttachments'},
        ),
    ]
