# Generated by Django 5.0 on 2023-12-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_orderattachment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
