# Generated by Django 5.0 on 2023-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
