# Generated by Django 5.0 on 2023-12-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_order_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expired',
        ),
    ]
