# Generated by Django 5.0 on 2023-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_order_creation_time_remove_order_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
