# Generated by Django 5.0 on 2023-12-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_order_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='expiration_date',
            new_name='creation_date',
        ),
    ]
