# Generated by Django 5.0 on 2023-12-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rename_expiration_date_order_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expired',
        ),
    ]
