# Generated by Django 5.0 on 2024-01-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_rating_rating_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_creator',
        ),
    ]
