# Generated by Django 5.0 on 2024-01-01 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_remove_rating_rating_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating_Creators', to=settings.AUTH_USER_MODEL)),
                ('rating_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rating_Subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
