# Generated by Django 5.0 on 2024-01-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_rating_relation_rating_user_attachments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_attachments',
            options={'verbose_name_plural': 'User_attachments'},
        ),
        migrations.RemoveField(
            model_name='user_attachments',
            name='ip',
        ),
        migrations.AlterField(
            model_name='user_attachments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_attachments', to=settings.AUTH_USER_MODEL),
        ),
    ]
