# Generated by Django 5.0 on 2024-01-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_alter_user_attachments_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating_relation',
            old_name='rating',
            new_name='comment',
        ),
    ]
