# Generated by Django 5.0 on 2024-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_rename_rating_rating_relation_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attachments',
            name='City',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_attachments',
            name='Country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_attachments',
            name='Postal_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_attachments',
            name='Street',
            field=models.CharField(default='', max_length=255),
        ),
    ]
