# Generated by Django 5.0 on 2024-01-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_user_attachments_city_user_attachments_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderattachment',
            options={'verbose_name_plural': 'Order_Attachments'},
        ),
    ]
