# Generated by Django 5.0.1 on 2024-01-07 18:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_alter_orderattachment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
