# Generated by Django 5.0.1 on 2024-01-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_alter_order_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAttachment',
        ),
    ]
