# Generated by Django 5.0.1 on 2024-01-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_delete_orderattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user_attachments',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
