# Generated by Django 5.0.1 on 2024-01-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_remove_order_mail_remove_order_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_attachments',
            name='Country',
        ),
    ]
