# Generated by Django 5.0.1 on 2024-01-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_remove_user_attachments_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attachments',
            name='theme',
            field=models.CharField(default='', max_length=255),
        ),
    ]
