# Generated by Django 5.0.1 on 2024-01-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_user_attachments_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
