# Generated by Django 5.0.1 on 2024-01-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_delete_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_images', to='homepage.order')),
            ],
            options={
                'verbose_name_plural': 'Order_images',
            },
        ),
    ]
