# Generated by Django 5.0.1 on 2024-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0033_order_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating_relation',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
