# Generated by Django 5.0.1 on 2024-02-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_rating_relation_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating_relation',
            name='rating',
        ),
    ]
