# Generated by Django 5.0.1 on 2024-02-01 16:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_remove_rating_relation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
