# Generated by Django 5.0.1 on 2024-02-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0036_alter_order_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_images',
        ),
    ]
