# Generated by Django 5.0.2 on 2024-02-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0037_delete_order_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
