# Generated by Django 5.0.2 on 2024-02-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_user_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_message',
            name='receiver',
        ),
    ]
