# Generated by Django 5.0.2 on 2024-02-17 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_remove_user_message_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_to', to='homepage.user_message')),
            ],
            options={
                'verbose_name_plural': 'Admin_Message',
            },
        ),
    ]
