# Generated by Django 5.0.2 on 2024-02-19 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_admin_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Message',
            new_name='Feedback',
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'User_Messages'},
        ),
        migrations.DeleteModel(
            name='Admin_Message',
        ),
    ]
