# Generated by Django 5.0.2 on 2024-02-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0042_rename_user_message_feedback_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
    ]
