# Generated by Django 5.0.2 on 2024-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
