# Generated by Django 5.0.2 on 2024-02-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0046_img_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img_message',
        ),
    ]
