# Generated by Django 4.2.5 on 2024-03-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_delete_img_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
