# Generated by Django 4.2.5 on 2024-03-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0048_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_attachments',
            name='offer_count',
            field=models.IntegerField(default=0),
        ),
    ]
