# Generated by Django 4.2.5 on 2024-03-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
